### ISSUE TITLE
Please provide an AppImage for download

### ISSUE THREAD

**Issue by probonopd** [MlemandPurrs/rapluslite#1]
https://github.com/MlemandPurrs/rapluslite/blob/54085674889c360211dfc9f91f038769e567a06b/engine/packaging/linux/buildpackage.sh#L2

Please provide an AppImage for download, thanks.

**Comment by MlemandPurrs** [comment]
just generated releases, https://github.com/MlemandPurrs/rapluslite/releases 
let me know if it oddly doesnt function.

**Comment by probonopd** [comment]
Mono needs to be bundled inside the AppImage since it cannot reasonably be expected to come with the default installation of every distribution. As per the AppImage philosophy, AppImages should have no dependencies other than what comes _by default_ with the base system.

```
RA Plus Lite Mod requires Mono 4.2 or greater and the cert-sync utility.
Please install Mono using your system package manager.
```

References:
* https://docs.appimage.org/introduction/concepts.html
* https://github.com/AppImage/AppImageKit/wiki/Bundling-Mono-apps

**Comment by MlemandPurrs** [comment]
i have inquired about this with the developers of OpenRA, they have stated that this issue already got adressed and will be fixed in the next playtest and release.
so, im sorry but there is nothing i can do about this issue until then.

**Comment by MlemandPurrs** [comment]
i have updated the mod to latest stable release, let me know if there is still an issue. https://github.com/MlemandPurrs/rapluslite/releases/tag/v1.3-beta-hotfix
